# Generated by Django 4.2.1 on 2023-05-24 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameVote', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=700)),
                ('imageVote', models.ImageField(default='voteDefault.jpeg', upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAuthor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
