# Generated by Django 4.2.1 on 2023-05-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0006_choose_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_vote',
            name='imageVote',
            field=models.ImageField(default='default.jpeg', upload_to=''),
        ),
    ]
