# Generated by Django 4.2.1 on 2023-05-29 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0007_alter_create_vote_imagevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_vote',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wishes.voteoption'),
        ),
    ]
