# Generated by Django 4.2.1 on 2023-05-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0008_create_vote_selected_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteoption',
            name='description_vote',
            field=models.CharField(blank=True, default='Default Description', max_length=700),
        ),
        migrations.AlterField(
            model_name='voteoption',
            name='image_description',
            field=models.ImageField(blank=True, default='voteDefault.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='voteoption',
            name='option_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
