# Generated by Django 4.2.1 on 2023-05-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0009_alter_voteoption_description_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_vote',
            name='description',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='create_vote',
            name='imageVote',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to=''),
        ),
    ]
