# Generated by Django 4.2.1 on 2023-05-30 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0010_alter_create_vote_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choose_option',
            name='vote',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='name_vote', to='wishes.create_vote'),
        ),
    ]
