# Generated by Django 4.2.1 on 2023-05-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0013_create_vote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_vote',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
