# Generated by Django 4.2.1 on 2023-06-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0015_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
