# Generated by Django 4.2.1 on 2023-06-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0016_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteoption',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
