# Generated by Django 4.2.1 on 2023-06-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0017_voteoption_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteoption',
            name='is_deleted',
        ),
    ]
