# Generated by Django 4.2.1 on 2023-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0018_remove_voteoption_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_vote',
            name='description',
            field=models.CharField(blank=True, default='Default Description', max_length=700),
        ),
        migrations.AlterField(
            model_name='create_vote',
            name='imageVote',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
