# Generated by Django 4.2.1 on 2023-08-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0019_alter_create_vote_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_vote',
            name='nameVote',
            field=models.CharField(max_length=100),
        ),
    ]
