# Generated by Django 4.2.1 on 2023-08-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0021_choose_option_has_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_vote',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
