# Generated by Django 4.2.1 on 2023-08-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0022_create_vote_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_vote',
            old_name='code',
            new_name='access_code',
        ),
    ]
