# Generated by Django 4.2.1 on 2023-08-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0023_rename_code_create_vote_access_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_vote',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='create_vote',
            name='duration_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
